
matrix:
  fast_finish: true 
  include:
    - language: python
      sudo: false
      python: "3.6"
      install:
        - pip install -e .[pythonz] --upgrade
        - pip install pytest
      script: py.test -rws tests/
    - language: python
      sudo: false
      arch: arm64
      python: "3.6"
      install:
        - pip install -e .[pythonz] --upgrade
        - pip install pytest
      script: py.test -rws tests/  
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      install:
        - pip install -e . --upgrade
        - pip install pytest
      script: py.test -rws tests/ --ignore=tests/test_install.py
    - language: python
      dist: xenial
      arch: arm64
      sudo: required
      python: "3.7"
      install:
        - pip install -e . --upgrade
        - pip install pytest
      script: py.test -rws tests/ --ignore=tests/test_install.py  
  allow_failures:
    - env: CHANNEL_HASH=nixos-unstable
